### ISSUE TITLE
This plugin had a weird behavior.

### ISSUE THREAD

**Issue by kftX** [frangarcj/oclockvita#1]
I dunno if you're gonna keep working on this or not, but I might as well create a ticket just in case.

I tried adding the plugin to my Ar NoSurge game (US version) in taiHEN's config.txt file and it didn't work at first.. Not only did it make the game error out throwing a C-12828-1 error, then everything else in the Vita stops working until I reboot and reapplyed taiHEN. Tested it twice with that behavior.

The third time I was gonna take screenshots to show you, and it worked. No idea what changed. Just creating this in case other people have this issue.

Thanks for the great plugin!

**Comment by fabwill** [comment]
im not sure how to edit the txt file, i put the game title and path like this:
*PCSB00294
ux0:tai/oclockvita.suprx

**Comment by ViZi9** [comment]
Hi fabwill how did u get it to work please help me.

**Comment by fabwill** [comment]
sure thing buddy
this how you edit the txt file, if anyone was having trouble:

# titleid for your game (this one is for Root//Letter for example)
*PCSB00294(this is an example, its ninja gaiden)
ux0:tai/oclockvita.suprx

*After you edited the text file restart your vita* (you press select+up to show menu and you press select+down to close menu)

**Comment by ViZi9** [comment]
:( man I did this on multiple games but when I start them they wont get passed the loading screen, i tried on cartridge+encrypted+decrypted games.

**Comment by ViZi9** [comment]
Do u have adrenaline? If so please show me where you put the code maybe it has something to do with the placement of the code.

**Comment by fabwill** [comment]
when you edited the txt file was it on all seperate lines

**Comment by ViZi9** [comment]
Yeah and there are no spaces between the codes so line 6 has a code and line 7 also has a code.

**Comment by fabwill** [comment]
let me show you mine, one sec

**Comment by ViZi9** [comment]
Ok :D

**Comment by fabwill** [comment]
![2017-01-01-140257](https://cloud.githubusercontent.com/assets/24864779/21582792/371f2a86-d02c-11e6-9b6d-613afc4bd398.jpg)
![2017-01-01-140304](https://cloud.githubusercontent.com/assets/24864779/21582794/3720438a-d02c-11e6-939c-a4add3c4c60b.jpg)
![2017-01-01-140252](https://cloud.githubusercontent.com/assets/24864779/21582793/371f5330-d02c-11e6-9713-73f8c1c6534d.jpg)

**Comment by ViZi9** [comment]
Thanks Bro :) will try now.

**Comment by fabwill** [comment]
no problem

**Comment by ViZi9** [comment]
Wow it worked perfectly fine thanks for your time :D + do u know if I can do multiple *Game at the same time?

**Comment by fabwill** [comment]
yes you can, just repeat the same thing for the first game in the next line, like i have in the photo, i have no problem with helping your welcome

**Comment by ViZi9** [comment]
Ayyy didn't see that sorry :( studying chemistry wrecked my freaking brain imma go sleep gn.

**Comment by frangarcj** [comment]
@kftX did it got solved?

**Comment by kftX** [comment]
I'm gonna test your new version later today (got articles to write) and I'll report back!

**Comment by kftX** [comment]
Nope it's still happening. I just updated your plugin and tried again, the game I mentioned in my first post froze to a black screen. Closed it and tried again and got greeted by a C1-2783-0 error. Trying to open any other app also doesn't work but with a C1-9654-4 error.
